### ISSUE TITLE
Refactor GitHub actions to use the composite install action

### ISSUE THREAD

**Issue by RayRedGoose** [Workday/canvas-kit#2107]
## 🚀 Feature Proposal

Refactor GitHub actions to use the composite `install` action from `Workday/canvas-kit-actions`. 

The next actions will be affected:
- canary
- forward-merge
- pull-request:
  - `install` job
  - `check` job
  - `build` job
  - `visual-test` job
  - steps

## Motivation

After refactoring `release` and `minor-release` actions, we can replace hard-coded install steps (caching and packages install) by calling the composite action. It allows cleaning repeated steps to increase code readability and to make action maintenance easier. Actual action code will be more visible and we don't need to change install steps in any instance, if we make any changes to this process.

## Example

Before refactor:

```yaml
# canary.yml workflow

steps:
  - uses: actions/checkout@v2
    with:
      persist-credentials: false
      fetch-depth: 0 

  - name: Get Cypress Version
    id: cypress-version
    run: echo "::set-output name=version::$(node utils/get-cypress-version.js)"
    
  - uses: actions/setup-node@v2.4.0
    with:
      node-version: 14.x
      registry-url: https://registry.npmjs.org

  - name: Cache node modules
    id: yarn-cache
    uses: actions/cache@v1
    with:
      path: node_modules
      key: ${{ runner.os }}-node-modules-hash-${{ hashFiles('yarn.lock') }}

  - name: Cache Cypress
    id: cypress-cache
    uses: actions/cache/@v1
    with:
      path: .cache/cypress
      key: ${{ runner.os }}-cypress-cache-version-${{ steps.cypress-version.outputs.version }}

  - name: Install Packages
    if:
      steps.yarn-cache.outputs.cache-hit != 'true' || steps.cypress-cache.outputs.cache-hit !=
      'true'
    run: yarn install --production=false
    env:
      CYPRESS_CACHE_FOLDER: .cache/cypress

  - name: Build Storybook
    run: |
      yarn build-storybook --quiet
      npx sb extract docs docs/stories.json

  - name: Build
    run: yarn build

  - name: Publish
    run: node utils/publish-canary.mjs
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_CI_PUBLISH_TOKEN}}
      SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
      BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      
  - name: Update Chromatic Baseline
    uses: chromaui/action@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
      storybookBuildDir: docs
      exitOnceUploaded: true
      exitZeroOnChanges: true
      autoAcceptChanges: true
```

After refactor:

```yaml
# canary.yaml workflow

steps:
  - uses: actions/checkout@v2
    with:
      persist-credentials: false
      fetch-depth: 0 
    
  - uses: Workday/canvas-kit-actions/install@v1
    with:
      node-version: 14.x

  - name: Build Storybook
    run: |
      yarn build-storybook --quiet
      npx sb extract docs docs/stories.json

  - name: Build
    run: yarn build

  - name: Publish
    run: node utils/publish-canary.mjs
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_CI_PUBLISH_TOKEN}}
      SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
      BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      
  - name: Update Chromatic Baseline
    uses: chromaui/action@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
      storybookBuildDir: docs
      exitOnceUploaded: true
      exitZeroOnChanges: true
      autoAcceptChanges: true
```
