### ISSUE TITLE
Generate CSS packages from React styles

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#2577]
## 🚀 Feature Proposal

Generate CSS Kit from React Kit. 

## Motivation

Less maintenance supporting a CSS kit and guarantee the CSS kit and React kit are up-to-date.

## Example

In the button package, the following should extract similar to below:

`modules/react/button/lib/Button.tsx`
```tsx
const buttonStencil = createStencil({
  base: {
    padding: 10
  },
  modifiers: {
    size: {
      large: {
        padding: 20
      }
    }
  }
})
```

`modules/css/button.css`
```css
.cnvs-button { padding: 10px; }
.cnvs-button--size-large { padding: 20px; }
```
