### ISSUE TITLE
Style transform always turns numbers into pixels.

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#2587]
## 🐛 Bug Report

The style transform always turns numbers into pixels which yields incorrect results.

For example, this input:
```tsx
const ANIMATION_DURATION_MS = 1230;

const styles = createStyles({
  animationDelay: `calc(${ANIMATION_DURATION_MS}ms * (1/3))`
})
```

will result in the following output:

```css
.className {
  animation-delay: calc(1230pxms * (1/3));
}
```

![image](https://github.com/Workday/canvas-kit/assets/338257/ac0fd2b6-260c-4654-86db-c35b64657b13)
