### ISSUE TITLE
Loading animations should not be live regions (CANVAS-1101)

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#792]
## 🐛 Bug Report

The loading animations have been partially implemented as live regions - when all that is needed is that they simply provide text equivalents for the animation for screen reader users. This is to meet WCAG 1.1.1 Non-text Content and 4.1.3 Status Messages.

## Found in
3.x and 4.x
 
## To Reproduce

For [Loading dots](https://workday.github.io/canvas-kit/?path=/story/components-indicators-loading-animation-react--loading-dots) and [Skeleton Loader](https://workday.github.io/canvas-kit/?path=/story/components-indicators-skeleton-react--complete) contain the following aria attributes making it a live region ` aria-label="Loading" aria-live="polite" role="status"`

## Expected Behavior

These loading div elements should not be configured as live regions, instead..

```html
<div class="wdc-loading-dots">
  <div class="sr-only">Loading</div>
  <span aria-hidden="true"><!-- animation here --></span>
</div>
```

```css
.sr-only {
  clip-path: inset(100%) !important;
  clip: rect(1px, 1px, 1px, 1px) !important;
  height: 1px !important;
  overflow: hidden !important;
  position: absolute !important;
  white-space: nowrap !important;
  width: 1px !important;
}
```

**Accessibility Contact - @mathalete**
